services:
  kafka:
    image: "docker.io/confluentinc/cp-kafka:7.7.7"
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    networks:
      - kafka-net
    
    # Kraft mode (no Zookeeper)
    environment:
      - KAFKA_KRAFT_MODE=true
      - CLUSTER_ID=pZ3K9nZ7R9S8vGmXvQF2sA
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

    # Listeners
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
    
    # storage
      - KAFKA_LOG_DIRS=/tmp/kraft-combined-logs

    volumes:
      - kafka-data:/var/lib/kafka/data

volumes:
  kafka-data:

networks:
  kafka-net:
    driver: bridge